services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"  # UI
      - "14268:14268"  # HTTP (jaeger.thrift)
      - "14250:14250"  # gRPC (OTLP)
      - "4317:4317"    # OTLP gRPC (padrão)
      - "4318:4318"    # OTLP HTTP (padrão)
      - "9411:9411"    # Zipkin
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=0.0.0.0:9411