global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Se suas apps expuserem m√©tricas Prometheus, adicione aqui
  - job_name: 'app-a'
    static_configs:
      - targets: ['host.docker.internal:8080']
  
  - job_name: 'app-b'
    static_configs:
      - targets: ['host.docker.internal:8081']
  
  - job_name: 'app-c'
    static_configs:
      - targets: ['host.docker.internal:8082']